### ISSUE TITLE
Keyboard autocomplete selection does not select autocomplete entry

### ISSUE THREAD

**Issue by zetokore** [agustinl/svelte-tags-input#95] opened 2024-06-21 15:58 UTC
If you click on the autocomplete entry, it selects the entry, but if you select via the keyboard, it only adds the currently typed value.

![image](https://github.com/agustinl/svelte-tags-input/assets/7066726/b5b2b295-0258-433a-b8d1-3e2c2b355cbe)

![image](https://github.com/agustinl/svelte-tags-input/assets/7066726/69e7fc78-fbd4-4c0f-8a46-96a25b32b42f)
```

let all_tags = [
    "logo"
]

<Tags 
	bind:tags={value}
	autoComplete={all_tags}
/>
```

Thank you for the great component!

**Comment by robluton** [comment] 2024-06-23 19:01
I submitted a PR for this issue, if you want to pull it down and give it a test run.
https://github.com/agustinl/svelte-tags-input/pull/96

**Comment by zetokore** [comment] 2024-06-24 02:28
Tested and looks good, thank you!

**Comment by agustinl** [comment] 2024-06-28 01:14
Hi guys!

Can't reproduce the issue. Could you test with the example [on the page](https://svelte-tags-input.vercel.app/)?

I search some country (first three letters), navigate with arrow keys, and added with tab.

**Comment by zetokore** [comment] 2024-06-28 02:52
@agustinl It works clicking tab but not clicking enter which I imagine is what most people will do.

**Comment by agustinl** [comment] 2024-06-29 16:01
Got it. Fix merged, and package published 🚀 
Thanks guys!

**Closed by agustinl** 2024-06-29 16:01 UTC
Labels: bug
